### ISSUE TITLE
Can it run in the same server where c9 IDE is present?

### ISSUE THREAD

**Issue by psociety** [pylonide/pylon#106]
First of all: Thank you for leading an alternative project to keep this excellent editor updated!

I want to have the original c9v3 IDE and Pylon in the same server, is it possible or they will interfere each other?
I tried looking for a pylon docker container but i didn't find any at docker hub.

**Comment by exsilium** [comment]
Hi @psociety , and thanks.. They shouldn't interfere as long as you bind them to different ports. Use a `-p` argument for `server.js` to define available port to bind on your machine. Cheers!

**Comment by psociety** [comment]
Ty for replying! I was afraid they would use same db paths or alike! :)
