### ISSUE TITLE
Linuxserver.io Container 

### ISSUE THREAD

**Issue by thelamer** [pylonide/pylon#111]
Feel free to close this issue at any time. 

Just a heads up that we are now consuming your current releases for our container library. 
https://hub.docker.com/r/linuxserver/pylon

I wanted to get your opinion on functionality , we have done a cloud9 image for some time now https://hub.docker.com/r/linuxserver/cloud9 based on their core SDK , and took the approach of branching and supplying different base environments. 

As of right now the initial release is just a bare minimum Alpine environment to run your app. 
What kind of environments  would you like to see installed ?

I was wondering if it would be possible to define the "home" folder for the .settings and .sessions , right now we symlink sessions but .settings is always stored in the projects working folder. 

I also wanted to know if you have any pointers on plugin support in the form of a user defined config file or env variable. Should we just support an array of GitHub endpoints for ingestion ?(user/name)

**Comment by exsilium** [comment]
Hi @thelamer , sorry for the radio silence as I've been busy on other fronts. This is awesome. I will surely check it out. I can't comment on what kind of extra environments and tools should be made available but I can help with the `.settings` and `.sessions` location. By default they reside on the workspace but we can introduce a overload for this.

**Comment by exsilium** [comment]
It was a breeze to run it via a container and I'll surely add it to the main README of future versions as it's the quickest way to test-run Pylon:

`docker run --name=pylon -e PUID=1000 -e PGID=1000 -e TZ=Europe/London -p 3131:3131 --restart unless-stopped linuxserver/pylon`

Again, thanks again for sharing.
