### ISSUE TITLE
all opened terminal is removed when refresh/connection drops out

### ISSUE THREAD

**Issue by 2anandkr** [pylonide/pylon#42]
## Spec
- ubuntu 16.04 (with build-essential)
- node 8.11.2 npm 6.1.0 ( have tested with node 8.9.4, 6.14.5, 5.12.0 as well! same error) 
- serving over nginx with https termination  
- command:  bin/cloud9.sh -l 0.0.0.0 -p 8181 --username=foo --password=bar
- using IDE from chrome 66 (win 10)

```
0|cloud9   |     at /home/anand/cloud9/plugins-server/cloud9.ide.terminal/tty.js:233:7
0|cloud9   |     at Array.forEach (<anonymous>)
0|cloud9   |     at Timeout._onTimeout (/home/anand/cloud9/plugins-server/cloud9.ide.terminal/tty.js:232:11)
0|cloud9   |     at ontimeout (timers.js:498:11)
0|cloud9   |     at tryOnTimeout (timers.js:323:5)
0|cloud9   |     at Timer.listOnTimeout (timers.js:290:5)
0|cloud9   | Error: Usage: pty.resize(fd, cols, rows)
0|cloud9   |     at UnixTerminal.resize (/home/anand/cloud9/node_modules/node-pty/lib/unixTerminal.js:213:13)
0|cloud9   |     at /home/anand/cloud9/plugins-server/cloud9.ide.terminal/tty.js:223:12
0|cloud9   |     at /home/anand/cloud9/plugins-server/cloud9.ide.terminal/tty.js:233:7
0|cloud9   |     at Array.forEach (<anonymous>)
0|cloud9   |     at Timeout._onTimeout (/home/anand/cloud9/plugins-server/cloud9.ide.terminal/tty.js:232:11)
0|cloud9   |     at ontimeout (timers.js:498:11)
0|cloud9   |     at tryOnTimeout (timers.js:323:5)
0|cloud9   |     at Timer.listOnTimeout (timers.js:290:5)
```
1. Is it that node-pty did not compile properly?   `pty.resize(...)` signature is not correct

**Comment by exsilium** [comment]
Hi, thanks for reporting - and for trying out cloud9v2 :star2: This is new, I'll take a look. The terminal session restore hasn't properly worked after moving from term.js/pty.js to xterm.js/node-pty. Further more, at least I have an issue as described in #30 where refresh/connection drop causes 100% CPU consumption on the server side when Chrome is used. This has lead me to avoid such scenarios all together but this issue shouldn't happen. Thanks again for reporting.

**Comment by exsilium** [comment]
Can you please try the following patch and let me know if the terminal window survives a refresh:
```
diff --git a/plugins-server/cloud9.ide.terminal/tty.js b/plugins-server/cloud9.ide.terminal/tty.js
index fbd0ff6..3cd911d 100644
--- a/plugins-server/cloud9.ide.terminal/tty.js
+++ b/plugins-server/cloud9.ide.terminal/tty.js
@@ -220,7 +220,7 @@ Session.prototype.sync = function() {
     // terminal has actually been resized.
     term.resize(cols + 1, rows + 1);
     queue.push(function() {
-      term.resize(cols, rows);
+      //term.resize(cols, rows);
     });
 
     // Send SIGWINCH to our processes, and hopefully
@@ -329,7 +329,7 @@ Session.prototype.handleMove = function(id, left, top) {
 Session.prototype.handleResize = function(id, cols, rows) {
   var terms = this.terms;
   if (!terms[id]) return;
-  terms[id].resize(cols, rows);
+  //terms[id].resize(cols, rows);
   terms[id].cols = cols;
   terms[id].rows = rows;
 };
```

**Comment by 2anandkr** [comment]
@exsilium thanks for taking the time for the issue.
## results after applying the patch
- **after refresh** 
   - terminals are not lost, but
   - default to the normal size. (does not retain any previous resizes)
   - initially all terminals are blank. I needed to hit enter to see where I was
- **after connection drop**
   - terminals stay in place, but
   - when connection is up again, all on screen terminals dissapear.

**Comment by exsilium** [comment]
The committed fix to development branch should at least stop from crashing the server side. However, the restore of the terminal doesn't always work because on socket termination `node-pty` usually does cleanup and kills the pty.

**Comment by 2anandkr** [comment]
@exsilium Thank for the partial fix. Also, you said earlier: 
> The terminal session restore hasn't properly worked after moving from term.js/pty.js to xterm.js/node-pty.

The reason to switch?
Also, I had used the paid c9.io service in the past. This issue did not occur then.

**Comment by 2anandkr** [comment]
Thanks @exsilium for the info. Hmm! Tmux seems to be a reliable way to persist sessions. Is there something we can do to achieve this reliability?

One of the primary use cases, I see for this IDE is doing coding in remote server & using its terminal interface to run tasks without logging in with ssh to the machine. But loosing onscreen terminal windows due to connection drop out in midst of some work might be a big problem. I'm curious to know if this problem might be specific to windows.

**Comment by exsilium** [comment]
The scenario you describe is how I also use c9v2. However, i'm not plagued by such frequent disconnections. Couple of things to get around this issue:

1. You either develop a habit of going into a `tmux` session whenever using the terminal
2. You add the following snippet to your `~./bashrc` that does it for you:
```
# TMUX
if which tmux >/dev/null 2>&1; then
    #if not inside a tmux session, and if no session is started, start a new session
    test -z "$TMUX" && (tmux attach || tmux new-session)
fi
```
But still, you'd need to open a terminal window and resize it every time you lose the connection. Not sure how often you have these kind of interruptions and if these workounds would be sufficient. Cheers!

**Comment by exsilium** [comment]
The original issue submitted is fixed, thus closing.
