### ISSUE TITLE
That tab in which a picture (with .png extension in my case) is opened can't be closed.

### ISSUE THREAD

**Issue by shujaatak** [pylonide/pylon#46]
No matter If I use shortcut `Alt+W` or click on the `Cross` or click on `Close Tab `in right click context menu, I can't close the tab!

For example there is a picture named screenshot.png, if I double click on it in the Left Files Explorer Window it will be opened in a new tab called screenshot.png but I can't close it afterwards. Even refreshing the window has no effect on it. 

I confirm that those opened tabs stay open even after restarting Cloud9.

**Comment by exsilium** [comment]
@shujaatak , Thanks for reporting. Issue confirmed. Will fix...

**Comment by exsilium** [comment]
Fixed in `development` branch, @shujaatak , do you have possibility to test this out? Cheers! :beers:

**Comment by shujaatak** [comment]
Thanks @exsilium - I will soon test it on my server as soon as I recover my development system.

**Comment by exsilium** [comment]
Delivered in `v2.2.2` and closing this as resolved.
