### ISSUE TITLE
window.applicationCache is undefined in Chrome 70 / Firefox 63

### ISSUE THREAD

**Issue by mchen6** [pylonide/pylon#57]
Dear pylon maintainer:

An error occured after I upgraded to Chrome 70 today and re-launch pylon IDE. It said window.applicationCache is undefined. Firefox has similar issue. And in this case IDE cannot open or edit any files. This issue can be reproduced on latest pylon ```master``` branch.

It looks as if window.applicationCache feature has been turned off in newer browser releases. Very appreciated if you could take a look to this.

The error output on Chrome console looks like below:

![1](https://user-images.githubusercontent.com/1168741/47615147-58167480-dae6-11e8-9a27-fff434c0f97b.png)

**Comment by exsilium** [comment]
Hi and thanks for the bug report - what steps are needed to reproduce this? Are you running in offline mode? I'm on FF Quantum 63 and Chromium 70 - haven't noticed this issue yet but I'll try to repro. Thanks!

**Comment by mchen6** [comment]
Thanks for your notice.

I clone pylon repo and ```npm i```, then launch it on my Ubuntu 16.04 box with below command:

```./bin/pylon.sh -w ~/tmp -l 10.0.0.130```

Then on my Win10 x64 machine I visited http://10.0.0.130:3131/ with Chrome 70 and FF Quantum 63, the same error can be reproduced.

> Hi and thanks for the bug report - what steps are needed to reproduce this? Are you running in offline mode? I'm on FF Quantum 63 and Chromium 70 - haven't noticed this issue yet but I'll try to repro. Thanks!

**Comment by exsilium** [comment]
Thank you for the details. I'll try to reproduce this. Can you also please add your `node` and `npm` versions? Thanks!

**Comment by mchen6** [comment]
My node and npm versions are ```v8.12.0``` and ```6.4.1``` respectively. Thanks.

**Comment by mchen6** [comment]
It seems appCache has been diabled on non-secure connection:
https://www.chromestatus.com/feature/5714236168732672
https://www.thesslstore.com/blog/firefox-require-https-appcache/

To verify this, I added an nginx secured proxy in front of pylon, and confirmed this issue has disappeared.

**Comment by exsilium** [comment]
Thanks for digging into this more. All my test instances are also behind nginx so that explains why I wasn't able to reproduce this. I'll look into this in more detail...

**Comment by mchen6** [comment]
It now works fine on ```development``` branch. Closing issue. Thanks.
