### ISSUE TITLE
Increase maximum upload file size

### ISSUE THREAD

**Issue by Codes4Fun** [pylonide/pylon#63]
I went through the history of the limit and didn't find a reason for the limit. https://github.com/pylonide/pylon/commit/d08c2ded1ccd9d55750711b22decbf989dd206a4

This task I think will involve testing different file sizes on different browsers/devices to see what can be handled successfully. I have successfully tested files less than 2GB in desktop chrome, larger files I think had problems and need to be investigated, I suspect an integer overflow.

It may also be determined whether or not this should be a user configurable setting, but that is not required.

The code that controls the limit is in https://github.com/pylonide/pylon/blob/master/plugins-client/ext.uploadfiles/uploadfiles.js

**Comment by exsilium** [comment]
Just curious what are the practical use cases for uploading such huge files via the UI? If it's a blocker then I don't see an issue to raise the hardcoded limit - It really should be user configurable. The default, however, should be considered some sane and safe value.

In production like instances Pylon most likely (at least it should) is running behind a forwarding proxy where the actual limiting of the client upload will happen anyways eg. like the `client_max_body_size` parameter of `nginx`.

**Comment by Codes4Fun** [comment]
There is no specific use case, I just came across this uploading various projects through the UI, a few which had big data files.

In my case I am using Pylon on a dedicated server in a LAN, not through the internet. Pylon is convenient to switch between computers/devices without having to setup a development environment on every one of them, and I don't have to use an external hard drive to move my development files between computers.

I'd like to note that Pylon currently uploads files in 256 KB chunks in separate XmlHttpRequests and appends them together on the server, so ```client_max_body_size``` which I read defaults to 1 MB would more than enough to allow big file uploads.

This does sound like it needs to be user configurable though.

**Comment by exsilium** [comment]
In that case I don't see the need to limit the upload size, feel free to change that value to a new default  within the scope of #61 :+1: The user configurable option can be implemented in the unknown future.

**Comment by exsilium** [comment]
I tested with this in MacOS Safari with a file 1+GB - I did get a warning about the tab using extensive amount of memory but other than that everything worked smoothly.
