### ISSUE TITLE
install help

### ISSUE THREAD

**Issue by rogersantosferreira** [pylonide/pylon#68]
Hi!
Can anyone help me with the install of Pylon? I can't manage to make it work :/

I'm trying to install pylon on Debian 9.9 (Strech). See the console response:

`npm WARN deprecated formidable@1.0.17: Old versions of Formidable are not compatible with the current Node.js; Upgrade to 1.2.0 or later
npm WARN lifecycle node-pty@0.7.8~install: cannot run in wd node-pty@0.7.8 node scripts/install.js (wd=/opt/bitnami/apache2/htdocs/pylon/node_modules/node-pty)
npm WARN lifecycle node-pty@0.7.8~postinstall: cannot run in wd node-pty@0.7.8 node scripts/post-install.js (wd=/opt/bitnami/apache2/htdocs/pylon/node_modules/node-pty)
> pln@2.4.0 postinstall /usr/lib/node_modules/pln
> if [ -d 'node_modules/ace' ]; then cd node_modules/ace; else mkdir -p node_modules; ln -s ../../ace node_modules/ace; ln -s ../../treehugger node_modules/treehugger; cd ../a
ce; fi; make clean pre_build; ./Makefile.dryice.js minimal; cd ../..; make worker; if [ -L 'node_modules/ace' ]; then rm node_modules/ace; rm node_modules/treehugger; rmdir no
de_modules; fi
rm -rf build
rm: cannot remove 'build': Permission denied
Makefile:34: recipe for target 'clean' failed
make: *** [clean] Error 1
/opt/bitnami/apache2/htdocs/pylon/node_modules/architect-build/copy.js:121
            throw e;
            ^
Error: EACCES: permission denied, open '/opt/bitnami/apache2/htdocs/pylon/node_modules/ace/lib/ace/snippets/apex.js'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1229:35)
    at write (/opt/bitnami/apache2/htdocs/pylon/node_modules/architect-build/copy.js:110:16)
    at Function.copy.file (/opt/bitnami/apache2/htdocs/pylon/node_modules/architect-build/copy.js:115:9)
    at addSnippetFile (/opt/bitnami/apache2/htdocs/pylon/node_modules/ace/Makefile.dryice.js:611:14)
    at /opt/bitnami/apache2/htdocs/pylon/node_modules/ace/Makefile.dryice.js:386:13
    at Array.forEach (<anonymous>)
    at buildAce (/opt/bitnami/apache2/htdocs/pylon/node_modules/ace/Makefile.dryice.js:384:15)
    at main (/opt/bitnami/apache2/htdocs/pylon/node_modules/ace/Makefile.dryice.js:63:9)
    at Object.<anonymous> (/opt/bitnami/apache2/htdocs/pylon/node_modules/ace/Makefile.dryice.js:678:5)
mkdir -p plugins-client/lib.ace/www/worker
mkdir: cannot create directory ‘plugins-client/lib.ace/www/worker’: Permission denied
Makefile:70: recipe for target 'plugins-client/lib.ace/www/worker/worker-language.js' failed
make: *** [plugins-client/lib.ace/www/worker/worker-language.js] Error 1`

My nodejs version is  12.2.0
My npm version is 6.9.0

Note: it is the first time I have tried some npm install. Sorry if my problem sounds a litte stupid.

There is some tutorial to install it? The instructions is too simple :/ on readme.

Thx in advance!

**Comment by exsilium** [comment]
Thanks for the report @rogersantosferreira ! To be honest, I haven't tried running Pylon using Node 12 - I need to get to that to try and reproduce the issue.

**Comment by exsilium** [comment]
Issue confirmed to be Node 12 specific - https://travis-ci.org/pylonide/pylon/builds/531824731

**Comment by exsilium** [comment]
Currently relating this to `node-pty` Node.js  v12 support: 

- microsoft/node-pty#279
- microsoft/node-pty#288

Current workaround is to use older version of node. Once `node-pty` version `0.9.0` gets released a dependency upgrade will be performed also for Pylon.

**Comment by rogersantosferreira** [comment]
Hi, exsilium! I thank you for your time to reproduce the problem. Anyway, I have been testing the install exactly with the software versions that you provide in readme.

I tried with 
- Node 4.9.1
- g++-4.9
- make
- Python 2.7 (Already installed at my Debina 9.9)

This is the error I got:
`npm ERR! Linux 4.9.0-9-amd64
npm ERR! argv "/root/.nvm/versions/node/v4.9.1/bin/node" "/root/.nvm/versions/node/v4.9.1/bin/npm" "i"
npm ERR! node v4.9.1
npm ERR! npm  v2.15.11
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! node-pty@0.7.8 install: `node scripts/install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the node-pty@0.7.8 install script 'node scripts/install.js'.
npm ERR! This is most likely a problem with the node-pty package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-pty
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls node-pty
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/bitnami/apache2/htdocs/pylon/npm-debug.log`

What can I do next?
Thanks again!

**Comment by exsilium** [comment]
@rogersantosferreira , sorry to hear that you are still having issues - it's still `node-pty` that fails to install. I recommend creating a new directory and try to just install node-pty by issuing commands:

- `npm i node-pty@0.7.8`
- `npm i node-pty@0.8.0`

Let me know if these work for you or if not, what's the log output.

Thanks!

**Comment by rogersantosferreira** [comment]
It worked! Kind of... the server of pylon is working, but I can't reach it.
Anyway, Exsilium, I thank you very much for your help.

After all, I'm just trying to install it on Google Cloud Platform (GCP) on bitnami stack, but without success. I can't make it work like I was expecting :/ Maybe it is a problem with GCP or with my little skill with this.

Thanks again. I will try at localhost! I really liked the idea of pylon!
